name: Upload Python Package in releases or pushs

on:
  push:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install basic dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      run: python -m build
    - name: Upload wheel to Artifacts
      if: github.event.name == 'push'
      uses: actions/artifact@v3
      with:
        name: 'Neis_API_dev_wheel'
        path: 'dist/*.whl'
    - name: Upload source to Artifacts
      if: github.event.name == 'push'
      uses: actions/artifact@v3
      with:
        name: 'Neis_API_dev_source'
        path: 'dist/*.tar.gz'
    - name: Upload wheel to Releases
      if: github.event.name == 'release'
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: dist/*.whl
        tag: ${{ github.ref }}
        file_glob: true
    - name: Upload source to Releases
      if: github.event.name == 'release'
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: dist/*.tar.gz
        tag: ${{ github.ref }}
        file_glob: true
    - name: Publish package
      if: github.event.name == 'release'
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
